version: '3'
services:
 #databases
  db:
    image: mysql:8.0
    container_name: db
    user: 1000:1000
    command: --default-authentication-plugin=mysql_native_password 
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./Database:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    container_name: adminer
    ports:
     - 8600:8080
    environment: 
      ADMINER_DEFAULT_SERVER: db


  #backend services
  map:
     container_name: map
     image: backend
     build:
       context: .
       dockerfile: ./Dockerfiles/backend
     ports:
       - 6000:5000
     volumes:
       - ./map:/target
       - ./env:/env
     command:  /wait-for-it.sh -t 200 db:3306 -- python3 ./target/server.py
  comm:
     container_name: comm
     image: backend
     ports:
       - 6200:5000
     volumes:
       - ./comm:/target
       - ./env:/env
     command:  /wait-for-it.sh -t 200 db:3306 -- python3 ./target/server.py
  user:  
    container_name: user
    image: backend
    ports:
       - 6400:5000
    restart: always
    volumes:
       - ./user:/target
       - ./env:/env
    command:  /wait-for-it.sh -t 200 db:3306 -- python3 ./target/server.py

#frontend   
  react:
    container_name: react
    image: react
    restart: always
    build:
        context: .
        dockerfile: ./Dockerfiles/react
    ports:
      - 7000:3000
    volumes:
      - ./react:/target
    command: npm start --prefix target
 
#forum

  mybb:
    container_name: mybb
    image: mybb/mybb:1.8.26
    volumes:
    - ./mybb:/var/www/html/:rw

 
#routing
  nginx:
    container_name: nginx
    restart: always   
    image: nginx  
    build:
      context: .
      dockerfile: ./Dockerfiles/nginx
    ports:
      - 3000:3000
      - 8080:80
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./mybb:/var/www/html:ro
    command: /wait-for-it.sh -t 200 map:5000 -- /wait-for-it.sh -t 200 user:5000 -- /wait-for-it.sh -t 200 comm:5000 -- /wait-for-it.sh -t 200 react:3000 -- nginx -g "daemon off";
  
#Passwords
  keycloak:
    container_name: keycloak
    restart: always   
    image: jboss/keycloak:latest
    build:
      context: .
      dockerfile: ./Dockerfiles/keycloak
    ports:
      - 8090:8443
    environment:
    # - KEYCLOAK_USER=admin
    # - KEYCLOAK_PASSWORD=admin
    - DB_VENDOR=mysql
    - DB_ADDR=db
    - DB_USER=${DB_USER}
    - DB_PASSWORD=${DB_PASSWORD}
    - DB_PORT=3306
    - DB_DATABASE=${DB_NAME}
    - KEYCLOAK_IMPORT=/tmp/key.json
    volumes:
     - ./keycloak:/tmp
  






