services:
  adminer:
    container_name: adminer
    environment:
      ADMINER_DEFAULT_SERVER: db
    image: adminer
    ports:
    - published: 8600
      target: 8080
    restart: always
  comm:
    command: /wait-for-it.sh -t 200 db:3306 -- gunicorn --workers 1 --bind 0.0.0.0:5000
      --chdir ./target server:app
    container_name: comm
    image: 127.0.0.1:5000/backend
    volumes:
    - /home/azureuser/Lolo/comm:/target:rw
    - /home/azureuser/Lolo/env:/env:rw
  db:
    command: --default-authentication-plugin=mysql_native_password
    container_name: db
    environment:
      MYSQL_DATABASE: lolo_db
      MYSQL_PASSWORD: 2EJW5vkLa7k$$@S
      MYSQL_ROOT_PASSWORD: Y3zbu4@AQ&kh!y
      MYSQL_USER: loloroot
    image: mysql:8.0
    restart: always
    user: 1000:1000
    volumes:
    - /home/azureuser/Lolo/Database:/var/lib/mysql:rw
  keycloak:
    build:
      context: /home/azureuser/Lolo
      dockerfile: ./Dockerfiles/keycloak
    container_name: keycloak
    environment:
      DB_ADDR: db
      DB_DATABASE: lolo_db
      DB_PASSWORD: 2EJW5vkLa7k$$@S
      DB_PORT: '3306'
      DB_USER: loloroot
      DB_VENDOR: mysql
      KEYCLOAK_IMPORT: /tmp/key.json
    image: 127.0.0.1:5000/jboss/keycloak:latest
    ports:
    - published: 8090
      target: 8443
    restart: always
    volumes:
    - /home/azureuser/Lolo/keycloak:/tmp:rw
  map:
    build:
      context: /home/azureuser/Lolo
      dockerfile: ./Dockerfiles/backend
    command: /wait-for-it.sh -t 200 db:3306 -- gunicorn --workers 1 --bind 0.0.0.0:5000
      --chdir ./target server:app
    container_name: map
    image: 127.0.0.1:5000/backend
    volumes:
    - /home/azureuser/Lolo/map:/target:rw
    - /home/azureuser/Lolo/env:/env:rw
  mybb:
    container_name: mybb
    image: mybb/mybb:1.8.26
    volumes:
    - /home/azureuser/Lolo/mybb:/var/www/html:rw
  nginx:
    build:
      context: /home/azureuser/Lolo
      dockerfile: ./Dockerfiles/nginx
    command: /wait-for-it.sh -t 200 map:5000 -- /wait-for-it.sh -t 200 user:5000 --
      /wait-for-it.sh -t 200 comm:5000 -- /wait-for-it.sh -t 200 react:3000 -- nginx
      -g "daemon off";
    container_name: nginx
    image: 127.0.0.1:5000/nginx
    ports:
    - published: 3000
      target: 3000
    - published: 8080
      target: 80
    restart: always
    volumes:
    - /home/azureuser/Lolo/nginx:/etc/nginx/conf.d:rw
    - /home/azureuser/Lolo/mybb:/var/www/html:ro
  react:
    build:
      context: /home/azureuser/Lolo
      dockerfile: ./Dockerfiles/react
    command: npm start --prefix target
    container_name: react
    image: 127.0.0.1:5000/react
    restart: always
    volumes:
    - /home/azureuser/Lolo/react:/target:rw
  user:
    command: /wait-for-it.sh -t 200 db:3306 -- gunicorn --workers 1 --bind 0.0.0.0:5000
      --chdir ./target server:app
    container_name: user
    image: 127.0.0.1:5000/backend
    restart: always
    volumes:
    - /home/azureuser/Lolo/user:/target:rw
    - /home/azureuser/Lolo/env:/env:rw
version: '3.2'

