services:
  keycloak:
    build:
      context: /home/azureuser/Lolo
      dockerfile: ./Dockerfiles/keycloak
    container_name: keycloak
    environment:
      DB_ADDR: db
      DB_DATABASE: lolo_db
      DB_PASSWORD: 2EJW5vkLa7k$$@S
      DB_PORT: '3306'
      DB_USER: loloroot
      DB_VENDOR: mysql
      KEYCLOAK_IMPORT: /tmp/key.json
    image: 127.0.0.1:5000/jboss/keycloak:latest
    ports:
    - published: 8090
      target: 8443
    restart: always
    volumes:
    - /home/azureuser/Lolo/keycloak:/tmp:rw
version: '3.2'

