const reports = [
  {
    id: 1,
    comment:
      'Many locusts here. Many locusts here. Many locusts here. Many locusts here.',
    date: '1/1/2021',
    time: '14:35',
    location: 'Kenya (extremely long name right here)',
    lat: 9.0501,
    long: 39.7501,
    type: 'Adult (brown)',
    path: 'https://i.ibb.co/smRzRC3/locust-wiki.jpg',
  },
  {
    id: 2,
    comment: 'Locusts hatching',
    date: '3/5/2021',
    time: '8:02',
    location: 'Kenya',
    lat: 9.0102,
    long: 39.7102,
    type: 'Hoppers',
    path: 'https://i.ibb.co/JvfHJQw/Locusts-feeding-wiki.jpg',
  },
  {
    id: 3,
    comment: 'Locusts hatching',
    date: '3/5/2021',
    time: '9:02',
    location: 'Kenya',
    lat: 9.0702,
    long: 39.7102,
    type: 'Hoppers',
    path: '../assets/reportpics/Locust1.PNG',
  },
  {
    id: 4,
    comment: 'Locusts hatching',
    date: '3/5/2021',
    time: '1:02',
    location: 'Kenya',
    lat: 9.0902,
    long: 39.7102,
    type: 'Hoppers',
    path: 'https://i.ibb.co/JvfHJQw/Locusts-feeding-wiki.jpg',
  },
  {
    id: 5,
    comment: 'Locusts hatching',
    date: '3/5/2021',
    time: '2:02',
    location: 'Kenya',
    lat: 9.1102,
    long: 39.7102,
    type: 'Hoppers',
    path: 'https://i.ibb.co/JvfHJQw/Locusts-feeding-wiki.jpg',
  },
  {
    id: 6,
    comment: 'Locusts hatching',
    date: '3/5/2021',
    time: '3:02',
    location: 'Kenya',
    lat: 9.1302,
    long: 39.7102,
    type: 'Hoppers',
    path: 'https://i.ibb.co/JvfHJQw/Locusts-feeding-wiki.jpg',
  },
  {
    id: 7,
    comment: 'Locusts hatching',
    date: '3/5/2021',
    time: '4:02',
    location: 'Kenya',
    lat: 9.1502,
    long: 39.7102,
    type: 'Hoppers',
    path: 'https://i.ibb.co/JvfHJQw/Locusts-feeding-wiki.jpg',
  },
  {
    id: 8,
    comment: 'Locusts hatching',
    date: '3/5/2021',
    time: '5:02',
    location: 'Kenya',
    lat: 9.1702,
    long: 39.7102,
    type: 'Hoppers',
    path: 'https://i.ibb.co/JvfHJQw/Locusts-feeding-wiki.jpg',
  },
  {
    id: 9,
    comment: 'Locusts hatching',
    date: '3/5/2021',
    time: '6:02',
    location: 'Kenya',
    lat: 9.1902,
    long: 39.7102,
    type: 'Hoppers',
    path: 'https://i.ibb.co/JvfHJQw/Locusts-feeding-wiki.jpg',
  },
  {
    id: 10,
    comment: 'Locusts hatching',
    date: '3/5/2021',
    time: '7:02',
    location: 'Kenya',
    lat: 9.2102,
    long: 39.7102,
    type: 'Hoppers',
    path: 'https://i.ibb.co/JvfHJQw/Locusts-feeding-wiki.jpg',
  },
  {
    id: 11,
    comment: 'Locusts hatching',
    date: '3/5/2021',
    time: '10:02',
    location: 'Kenya',
    lat: 9.2302,
    long: 39.7102,
    type: 'Hoppers',
    path: 'https://i.ibb.co/JvfHJQw/Locusts-feeding-wiki.jpg',
  },
  {
    id: 12,
    comment: 'Locusts hatching',
    date: '3/5/2021',
    time: '11:02',
    location: 'Kenya',
    lat: 9.2502,
    long: 39.7102,
    type: 'Hoppers',
    path: 'https://i.ibb.co/JvfHJQw/Locusts-feeding-wiki.jpg',
  },
  {
    id: 13,
    comment: 'Locusts hatching',
    date: '3/5/2021',
    time: '12:02',
    location: 'Kenya',
    lat: 9.2702,
    long: 39.7102,
    type: 'Hoppers',
    path: 'https://i.ibb.co/JvfHJQw/Locusts-feeding-wiki.jpg',
  },
  {
    id: 14,
    comment: 'Locusts hatching',
    date: '3/5/2021',
    time: '14:02',
    location: 'Kenya',
    lat: 9.2902,
    long: 39.7102,
    type: 'Hoppers',
    path: 'https://i.ibb.co/JvfHJQw/Locusts-feeding-wiki.jpg',
  },
  {
    id: 15,
    comment: 'Locusts hatching',
    date: '3/5/2021',
    time: '13:02',
    location: 'Kenya',
    lat: 9.3102,
    long: 39.7102,
    type: 'Hoppers',
    path: 'https://i.ibb.co/JvfHJQw/Locusts-feeding-wiki.jpg',
  },
  {
    id: 16,
    comment: 'Locusts hatching',
    date: '3/5/2021',
    time: '15:02',
    location: 'Kenya',
    lat: 9.3302,
    long: 39.7102,
    type: 'Hoppers',
    path: 'https://i.ibb.co/JvfHJQw/Locusts-feeding-wiki.jpg',
  },
  {
    id: 17,
    comment: 'Locusts hatching',
    date: '3/5/2021',
    time: '16:02',
    location: 'Kenya',
    lat: 9.3502,
    long: 39.7102,
    type: 'Hoppers',
    path: 'https://i.ibb.co/JvfHJQw/Locusts-feeding-wiki.jpg',
  },
  {
    id: 18,
    comment: 'Locusts hatching',
    date: '3/5/2021',
    time: '17:02',
    location: 'Kenya',
    lat: 9.3702,
    long: 39.7102,
    type: 'Hoppers',
    path: 'https://i.ibb.co/JvfHJQw/Locusts-feeding-wiki.jpg',
  },
  {
    id: 19,
    comment: 'Locusts hatching',
    date: '3/5/2021',
    time: '18:02',
    location: 'Kenya',
    lat: 9.3902,
    long: 39.7102,
    type: 'Hoppers',
    path: 'https://i.ibb.co/JvfHJQw/Locusts-feeding-wiki.jpg',
  },
  {
    id: 20,
    comment: 'Locusts hatching',
    date: '3/5/2021',
    time: '19:02',
    location: 'Kenya',
    lat: 9.4102,
    long: 39.7102,
    type: 'Hoppers',
    path: 'https://i.ibb.co/JvfHJQw/Locusts-feeding-wiki.jpg',
  },
]

export default reports
