name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    


jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
#     - name: Build the Docker image
#       run: docker-compose build
#     - name: Run the Container
#       run: docker-compose up -d 
#     - run: curl localhost:3000
    - run:
          if [["${#TAG_LIST[@]}" -ne 3 ]]; then
          echo "$RELEASE_VERSION is not a valid semantic version"
          exit 1
          fi
    - run: sudo apt install net-tools -y
    - run: netstat -ntlp | grep LISTEN

