name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    


jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker-compose build
    - name: Run the Container
      run: docker-compose up -d
    - run: curl localhost:3000
    - run: curl localhost:3000/api/map/test
    - run: curl localhost:3000/api/comm/test   
    - run: curl localhost:3000/api/user/test   
